### ISSUE TITLE
Creating a development environment

### ISSUE THREAD

**Issue by fakhruddinpattan** [CSCI-GA-2820-SP23-003/wishlists#13]
**Create a development environment to test the implemented functionalities before moving to the production.**
 ### Details and Assumptions
 * This particular developemnent environment must be dedicated to wishlists team so that our testing will not be blocked by other teams implementations.
 * Lastest code will be released to development environment after every build. 
 ### Acceptance Criteria
 * Development environment must have all the implementations available in the project.
 * The development environment should be available and accessible to all team members.

**Comment by reubenabraham** [comment]
Closing this ticket since it's not required.
