### ISSUE TITLE
Tables

### ISSUE THREAD

**Issue by sorongisme** [CSCI-GA-2820-SP23-003/wishlists#4]
1. Users
2. Products
3. Wishlists

Further tasks
1. Need to see which fields we need for each table.
2. Which field should be the Primary key
3. These are basic tables, what tables do we need more of in the future? (Reviews.. etc)

**Comment by jjrofrano** [comment]
You don't need a table for Users or Products. The Customer service and the Products Service will take care of these. You only need to create a field for the user id and a field for the product id. That is all you need for get any information you may need from those other services as needed.

You will need a two tables however, one for **Wishlists** and one for **Items** that are in the wishlist. That should be the focus of your service.
