### ISSUE TITLE
Implement User Interface for Create wishlist

### ISSUE THREAD

**Issue by sorongisme** [CSCI-GA-2820-SP23-003/wishlists#44]
**As a** developer
**I need** the ability to implement a UI for Create wishlist
**So that** I don't need to use Postman for sending API Requests.
   
 ### Details and Assumptions
 * Add elements for creating a wishlist in the UI file.
 * BDD scenarios for creating wishlists will also be a part of this story.
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given the application is running
 When a wishlist is created through the UI
 Then it should be persisted in the database
```

**Comment by sakshamgarg** [comment]
We need to have separate user stories for each of the 7 endpoints. So we can convert this issue to one of the endpoint and then create 6 separate issues for other endpoints.
