### ISSUE TITLE
Add Swagger annotations to wishlist services to document REST API using Flask RESTX.

### ISSUE THREAD

**Issue by fakhruddinpattan** [CSCI-GA-2820-SP23-003/wishlists#53]
As a developer
I need add Swagger annotations to wishlist service
So that I can document REST API using Flask-RESTX

### Acceptance Criteria
Given the wishlist service is up and running
When Swagger annotations are added to the Wishlist service 
Then I can document REST API using Flask-RESTX.

**Comment by reubenabraham** [comment]
Task completed as a part of earlier Flask Restx ticket, so closing
