### ISSUE TITLE
Add Swagger data models to document the API payloads.

### ISSUE THREAD

**Issue by fakhruddinpattan** [CSCI-GA-2820-SP23-003/wishlists#55]
As a Developer
I need to add Swagger data models
So that I can document the API payloads

### Acceptance Criteria
Given the services are up and running 
When I add Swagger data models
Then I can document the API payloads

**Comment by sakshamgarg** [comment]
This ticket has already been created. Its a duplicate of this https://github.com/CSCI-GA-2820-SP23-003/wishlists/issues/49. Kindly close this.
