### ISSUE TITLE
Update the VS Code extension format

### ISSUE THREAD

**Issue by sakshamgarg** [CSCI-GA-2820-SP23-003/wishlists#6]
**Describe the bug**
VSCode has changed the way that extensions get loaded in the .devcontainers/devcontainer.json file. 

**To Reproduce**
1. Open this project in VS Code and reopen it using container.
2. There will be no extensions loaded in the extension tab on the left.

**Expected behavior**
The specified extensions should get loaded as per the .devcontainers/devcontainer.json file.

**Observed behavior**
No extensions are loaded in the project.

**Additional context**
The solution is available at https://github.com/nyu-devops/project-template/blob/master/.devcontainer/devcontainer.json

**Comment by reubenabraham** [comment]
Approved and merged. Moving this ticket to done.
