### ISSUE TITLE
Ability to read all the wishlist for the specific users

### ISSUE THREAD

**Issue by fred0405** [CSCI-GA-2820-SP23-003/wishlists#8]
**As a** User
**I need** to get a list of their wishlists
**So that** users can view the wishlists they have
   
 ### Details and Assumptions
 * Read the wishlists from certain users 
 *  The Api endpoint should be like `GET /wishlists`
 * It will return all of the wishlists owned by the user
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given there are wishlists in the database
 When the users want to see their wishlists
 Then the data should be fetched from the database
```

**Comment by reubenabraham** [comment]
Closing this ticket because it is redundant. List and Read will only have one end-point each, and this ticket is basically replicating the List endpoint functionality.
